---
name: libCommand
main: blugin\lib\libCommand
version: 1.2.1
api: [3.0.0]
authors: ['Blugin-team', 'PresentKim']
description: "[lib] Command library with multiple functions"
mcpe-protocol: [407, 408]
...