---
name: libCommand
main: blugin\lib\libCommand
version: 1.0.0
api: [4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: "[lib] Command library with multiple functions"
depend: [libTranslator]
...